### ISSUE TITLE
Error `context3.active is not a function` when testing node example

### ISSUE THREAD

**Issue by garysassano** [dev7a/lambda-otlp-forwarder#9]
I tested [this example](https://github.com/dev7a/lambda-otlp-forwarder/tree/main/packages/node/exporter#aws-lambda-usage) in a Node.js 22 Lambda function and received the following error:

```json
{
  "errorType": "TypeError",
  "errorMessage": "context3.active is not a function",
  "trace": [
    "TypeError: context3.active is not a function",
    "    at exports.handler (/var/task/index.js:30622:29)",
    "    at Runtime.handleOnceNonStreaming (file:///var/runtime/index.mjs:1173:29)"
  ]
}
```

**Comment by alessandrobologna** [comment]
Likely my bad. Can you try to rename the context in this line: https://github.com/dev7a/lambda-otlp-forwarder/blob/main/packages/node/exporter/README.md?plain=1#L92 
```
exports.handler = async (event, lambdaContext) => {
```
basically the context parameter has a name clash with this:
```
const { trace, SpanKind, context, propagation } = require('@opentelemetry/api');
```

**Comment by garysassano** [comment]
I confirm renaming the `context` parameter to `lambdaContext` fixed the issue.

**Comment by alessandrobologna** [comment]
thank you, and sorry for the distraction.
